config/routes.rb
Timetracker::Application.routes.draw do

  devise_for :users

  root :to=>'dashboard#show'

  resources :projects do
    resources :tasks do
      collection do
        get :search
      end
    end
  end
  
  resources :journal_entries do
    resources :tags do
      member do
        delete :untag
      end
    end
  end
  
  resources :tasks do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end
   
  resources :activities
  resources :journal_entries
  resources :tags
  
  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
    resources :states do
      member do
        get :make_default
      end
    end
    resources :tags
    resources :activities
  end
  
  put '/admin/users/:user_id/permissions', :to => 'admin/permissions#update',
          :as => :update_user_permissions
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability
    def initialize(user)
      user.permissions.each do |permission|
        can permission.action.to_sym, permission.permissions_apply_type.constantize do |permissions_apply |
        permissions_apply.nil? ||
        permission.permissions_apply_id.nil? ||
        permission.permissions_apply_id == permissions_apply.id
      end
    end
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  validates :name, :presence=>true
  validates :identifier, :uniqueness=>true
  def self.labels
    activities = self.all(:select=>"identifier,name, id", :order=>'name')
    out = activities.map do |activity|
       {:label=>"#{activity.identifier} #{activity.name}", :id=>activity.id}
    end
    out.to_json
  end
  def label
    "#{identifier} #{name}"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  before_create :set_previous_state
  after_create :set_task_state

  belongs_to :task
  belongs_to :user
  belongs_to :state
  belongs_to :previous_state, :class_name => "State"

  validates :text, :presence => true

  delegate :project, :to => :task
  
  private

  def set_previous_state
    self.previous_state = task.state
  end

  def set_task_state
    self.task.state = self.state
    self.task.save!
  end

end

app/models/journal_entry.rb
class JournalEntry < ActiveRecord::Base
  belongs_to :activity
  belongs_to :task
  belongs_to :user
  has_and_belongs_to_many :tags
  
  validates :duration, :presence=>true
  validates :activity, :presence=>true
  validates :user, :presence=>true
  
  def tag!(tagsparam)
    self.tags.clear
    Tag.find(tagsparam.split(',')).each do |newtag|
      self.tags << newtag
    end
  end

  def tagstring
    out = tags.map{|tag|tag.name}
    out.join(" ")
  end

end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :permissions_apply, :polymorphic=>true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, :dependent=>:destroy 

  validates :name, :presence => true, :uniqueness => true

  has_many :permissions, :as => :permissions_apply

  scope :readable_by, lambda { |user|
    joins(:permissions).where(:permissions => { :action => "view",:user_id => user.id })
  }
  
  def self.for(user)
    user.admin? ? Project : Project.readable_by(user)
  end
  
end

app/models/project_comment.rb
class ProjectComment < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :state
end

app/models/report.rb
class Report 
  
  attr_accessor  :title, :data, :columns, :start_date, :through_date, :detail_level,:subject,:current_row, :workbook, :worksheet
  
  #DETAIL_LEVELS= %w(project allocation task task_detail)
  #SUBJECTS= %w(project allocation tag person date) 
  
  def initialize(title)
    @title = title
  end
  
end

app/models/state.rb
class State < ActiveRecord::Base
  
  def to_s
    name
  end
  
  def default!
    current_default_state = State.find_by_default(true)
    self.default = true
    self.save!
    if current_default_state
      current_default_state.default = false
      current_default_state.save!
    end
  end
    
end

app/models/stretch.rb
class Stretch < ActiveRecord::Base
  validates :duration, :presence=>true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :state
  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :tags
  validates :title, :presence => true
  validates :description, :presence => true, :length=>{:minimum=>10}
  
  def tag!(tags)
    tags = tags.split(" ").map do |tag|
      Tag.find_or_create_by_name(tag)
    end
    self.tags << tags
  end
  
  def tagstring
    out = tags.map{|tag|tag.name}
    out.nil? ? '' : out.join(', ')
  end
  
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :permissions 
  
  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end
end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController

  before_filter :authenticate_user!#, :only => [:index, :show]
  before_filter :find_journal_entry, :only=>[:show, :edit, :update, :destroy]
  
  respond_to :xml, :xls, :json
  
  def index
    @q = JournalEntry.search(params[:q])
    @journal_entries = @q.result(:distinct=>true)
    params[:q].nil? ? @raw_search = 'All' : @raw_search=params[:q].to_s
    respond_to do |format|
      format.html
      format.xml do
        render :xml => @q.result(:distinct=>true).to_xml(:dasherize => false) 
      end
      format.xls do
        render :layout => false
        headers['Content-Disposition'] = "attachment; filename=\"journal_entries_search#{depunctuate(@raw_search).downcase}_#{fmt_file_date(Time.new)}.xls\""
        headers['Cache-Control'] = ''
      end
    end
  end
  
  def show

  end
  
  def new
    @journal_entry=JournalEntry.new
    @activities = Activity.all
  end
  
  def create
    params[:journal_entry][:user_id]= current_user.id
    @journal_entry = JournalEntry.new(params[:journal_entry])
    if @journal_entry.save
      @journal_entry.tag!(params[:tags]) #if params[:tags]
      flash[:notice] = "Journal Entry has been created."
      redirect_to @journal_entry
    else
      flash[:alert] = "Journal Entry has not been created."
      render :action => 'new'
    end
  end
  
  def edit
    @activities = Activity.all
    @tagsjson = @journal_entry.tags.to_json
  end

  def update
    params[:journal_entry][:user_id]= current_user.id
    if @journal_entry.update_attributes(params[:journal_entry])
      @journal_entry.tag!(params[:tags]) #if params[:tags]
      flash[:notice] = "Journal Entry has been updated."
      redirect_to @journal_entry
    else
      flash[:alert] = "Journal Entry has not been updated."
      render :action => "edit"
    end
  end
  
  def destroy
    @journal_entry.destroy
    flash[:notice] = "Journal Entry has been deleted."
    redirect_to journal_entries_path
  end

  private
  def find_journal_entry
    @journal_entry = JournalEntry.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The journal entry you were looking" +
    " for could not be found."
    redirect_to journal_entries_path
  end


end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/stretches_helper.rb
module StretchesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def state_for(comment)
    content_tag(:div, :class => "states") do
      if comment.state
        if comment.previous_state && comment.state != comment.previous_state
          "#{render comment.previous_state} &rarr; #{render comment.state}".html_safe
        else
          render(comment.state).html_safe
        end
      end
    end
  end
end

app/views/journal_entries/_form.html.erb
<%= form_for(@journal_entry) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :recorded_on %>
    <%= f.text_field :recorded_on %>
  </p>
  <p>
    <%= f.label :duration %>
    <%= f.text_field :duration %>
  </p>
  <p>
    <%= f.label :starting_quarter %>
    <%= f.text_field :starting_quarter %>
  </p>
  <p>
    <%= f.label :note %>
    <%= f.text_field :note %>
  </p>
  <p>
    <%= label_tag :activity_name, 'Activity' %>
    <%= f.hidden_field :activity_id %>
    <span id='activity_name' ><%=@journal_entry.activity.label %></span><br />
    Change to: <%= text_field_tag :activity_autoselect %>
  </p>

  <p>
    <%= label_tag :tags %>
    <%= text_field_tag :tags %>
  </p>

  <%= f.submit %>
<% end %>

app/views/journal_entries/edit.html.erb
<h2>Edit Journal Entry</h2>
<%= render "form", :locals=>{:activities=>@activities} %>

<script>
$(document).ready(function(){
  $("#tags").tokenInput('/tags.json/',{queryParam:'q[name_cont]', prePopulate:<%=@tagsjson.html_safe%>});
 var activity_list = eval(<%= Activity::labels.to_json.html_safe%>) 	

	$( "#activity_autoselect" ).autocomplete({
		source: activity_list,
		minLength: 2,
		select: function( event, ui ) {
				//alert("Selected: " + ui.item.label + " aka " + ui.item.id);
				$('#journal_entry_activity_id').val(ui.item.id);
				$('#activity_name').text(ui.item.label);
  	}
	});

});
</script>

app/views/journal_entries/index.html.erb
<h2>Journal Entries</h2>
<%#=@raw_search%><br />
<%=link_to "Permalink", request.url.html_safe%> || 
<% if @raw_search=='All'%>
  <%=link_to "Report", "#{request.url.html_safe}?format=xls"%>
<% else %>
  <%=link_to "Report", "#{request.url.html_safe}&format=xls"%> ||
  <%= link_to "View All", journal_entries_path %>
<%end%>
<table id='entry_results' border='1'>
  <thead>
    <tr>
    <th>&nbsp;</th>
    <%= search_form_for @q, :url=>journal_entries_path do |f| %>
      <th><%= f.label :recorded_on_gteq, "Recorded >=" %>
      <%= f.text_field :recorded_on_gteq, :size=>10 %><br />
      <%= f.label :recorded_on_lteq, "Recorded <=" %>
      <%= f.text_field :recorded_on_lteq, :size=>10 %></th>
      <th><%= f.label :duration_eq %>
      <%= f.text_field :duration_eq, :size=>10 %></th>
      <th>Start</th>
        <th><%= f.label :note_cont, "Note" %>
      <%= f.text_field :note_cont, :size=>10 %></th>
      <th><%= f.label :activity_identifier_cont, "Activity Ident"%>
      <%= f.text_field :activity_identifier_cont, :size=>10%></th>
      <th><%= f.label :activity_name_cont, "Activity" %>
      <%= f.text_field :activity_name_cont, :size=>10 %></th>
        <th><%= f.label :tags_name_cont, "Tags" %>
      <%= f.text_field :tags_name_cont, :size=>10 %></th>
        <th><%= f.label :user_name_cont, "User" %>
      <%= f.text_field :user_email_cont, :size=>10 %></th>
       <th><%= f.submit %></th>
    <% end %>
    </tr>
  </thead>
  <tbody>
    <% @journal_entries.each do |journal_entry| %>
      <tr>
        <td><%= link_to "View", journal_entry %></td>
        <td><%= journal_entry.recorded_on %></td>
        <td><%= journal_entry.duration %></td>
        <td><%= journal_entry.starting_quarter%></td>
        <td><%= journal_entry.note %></td>
        <td><%= journal_entry.activity.identifier %></td>
        <td><%= journal_entry.activity.name %></td>
        <td><%= journal_entry.tagstring %></td>
        <td><%= journal_entry.user.email %></td>
      </tr>   
    <% end %>
  </tbody>
</table>
<%= link_to "New Journal Entry", new_journal_entry_path %>
<script>
$(document).ready(function(){
  $("#q_recorded_on_gteq").datepicker({dateFormat:'yy-mm-dd'});
  $("#q_recorded_on_lteq").datepicker({dateFormat:'yy-mm-dd'});
});
</script>

app/views/journal_entries/new.html.erb
<h2>New Journal Entry</h2>
<%= render 'form', :locals=>{:activities=>@activities}%>
<script>
$(document).ready(function(){
  $("#tags").tokenInput('/tags.json/',{queryParam:'q[name_cont]'});
});
</script>

app/views/journal_entries/show.html.erb
<% title(@journal_entry.note, "Journal Entries") %>
<h2><%= @journal_entry.recorded_on %> || <%= @journal_entry.starting_quarter %> || <%= @journal_entry.duration%> || <%= @journal_entry.note%></h2>
  <div id='tags'><%= render @journal_entry.tags %></div>
<%= link_to "Edit Journal Entry", edit_journal_entry_path(@journal_entry) %>
<%= link_to "Delete Journal Entry", @journal_entry, :method => :delete,
:confirm => "Are you sure you want to delete this journal entry?" %>